# Generated by Django 5.1.1 on 2026-02-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_department_expense_feecollection_salary_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("event_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("class_name", models.CharField(max_length=80)),
                ("term", models.CharField(max_length=40)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HostelRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_name", models.CharField(max_length=150)),
                ("room_number", models.CharField(max_length=20)),
                ("check_in_date", models.DateField()),
                ("guardian_contact", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="LibraryBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("author", models.CharField(max_length=120)),
                ("isbn", models.CharField(max_length=30, unique=True)),
                ("copies_available", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SportsActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_name", models.CharField(max_length=120)),
                ("coach_name", models.CharField(blank=True, max_length=120)),
                ("activity_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("route_name", models.CharField(max_length=120)),
                ("driver_name", models.CharField(max_length=120)),
                ("vehicle_number", models.CharField(max_length=30)),
                ("pickup_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("exam_date", models.DateField()),
                ("total_marks", models.PositiveIntegerField(default=100)),
                ("subject", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="school.subject")),
            ],
        ),
        migrations.CreateModel(
            name="TimeTableEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("class_name", models.CharField(max_length=80)),
                ("day", models.CharField(choices=[("Monday", "Monday"), ("Tuesday", "Tuesday"), ("Wednesday", "Wednesday"), ("Thursday", "Thursday"), ("Friday", "Friday"), ("Saturday", "Saturday")], max_length=20)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("subject", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="school.subject")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="school.teacher")),
            ],
        ),
    ]
