# Generated by Django 6.0.2 on 2026-04-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
