# Generated by Django 6.0.2 on 2026-04-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_teacher_department_remove_teacher_user'),
        ('student', '0006_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.teacher'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.teacher'),
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='hostelrecord',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='feecollection',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='hostelrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='salary',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
