# Generated by Django 6.0.2 on 2026-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ROWJi9jFZT8n7Gj7WCILC0cy2RddYIYL', editable=False, max_length=32, unique=True),
        ),
    ]
