# Generated by Django 6.0.2 on 2026-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gxRtF6hqRixbkJvvE0e7wRGdmEx7UrbX', editable=False, max_length=32, unique=True),
        ),
    ]
